name: real_time_pawn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  logger: ^2.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  google_fonts: ^6.2.1
  page_transition: ^2.2.1
  flutter_animate: ^4.5.2
  csv: ^6.0.0
  file_picker: ^10.2.0
  data_table_2: ^2.6.0
  syncfusion_flutter_datagrid: ^30.1.40
  flutter_charts: ^0.5.2
  pie_chart: ^5.4.0
  loading_animation_widget: ^1.3.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  csc_picker_plus: ^0.0.3
  animated_introduction: ^1.0.3
  introduction_screen: ^3.1.17
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  fluttertoast: ^8.2.1
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  image_picker: ^1.2.0
  supabase_flutter: ^2.9.1
  photo_view: ^0.15.0
  video_player: ^2.10.0
  chewie: ^1.12.1
  readmore: ^3.0.0
  jwt_decoder: ^2.0.1
  pinput: ^5.0.1
  connectivity_plus: ^6.1.5
  lottie: ^3.3.2
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.1.1
  iconsax: ^0.0.8
  flutter_custom_clippers: ^2.1.0
  flutter_secure_storage: 
  # carousel_slider: ^4.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
